
resources:
  - name: registry_data_generator_repo
    type: GitRepo
    configuration:
      gitProvider: EldadaGitHub
      path: eldada/registry-data-generator
      branches:
        include: main

pipelines:
  - name: build_registry_data_docker_image

    steps:
      - name: step_1_docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: eldada.jfrog.io/docker/docker-data-generator
#          dockerImageTag: 0.${run_number}
          dockerImageTag: "0.14"
          inputResources:
            - name: registry_data_generator_repo
          integrations:
            - name: EldadaArtifactory

      - name: step_2_docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker
          integrations:
            - name: EldadaArtifactory
          inputSteps:
            - name: step_1_docker_build
